# Generated by Django 4.0.3 on 2022-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('users', '0002_profile_dob_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(to='article.category'),
        ),
    ]
